export default {
  harvesting: [
    'Husbandry',
    'Farming',
    'Fishing',
    'Logging',
    'Gathering',
    'Mining',
  ],
  refining: [
    'Alchemy',
    'Cooking',
    'Handicrafts',
    'Machining',
    'Metalwork',
    'Printing',
    'Masonry',
    'Tailoring',
    'Leatherwork',
    'Weaponry',
    'Carpentry',
  ],
  misc: [
    'Construction',
    'Larceny',
    'Commerce',
    'Artistry',
    'Exploration',
  ],
};
